train:
  batch_size: 30
  shuffle: true
  num_workers: 10
  learning_rate: 0.0001
  num_epochs: 120
  # log_path: "./evaluate/wrinkle/resnet/loss_log_wrinkle_train.csv"
  # json_path: "./weight/wrinkle/resnet/loss_log_wrinkle_train.json"
  # model_save_path: "./weight/wrinkle/resnet/best_model_NIA_wrinkle_classify.pth"
  use_lr_scheduler: true   # 是否启用学习率调度器
  lr_scheduler:
    step_size: 30          # 学习率下降的步长（每多少个epoch下降一次）
    gamma: 0.1             # 学习率下降幅度

dataset:
  train_img_path: "/data1/NIA/Training/img/TS"
  train_json_path: "/data1/NIA/Training/label/TL"
  val_img_path: "/data1/NIA/Validation/img/VS"
  val_json_path: "/data1/NIA/Validation/label/VL"
  selected_devices: ["01"]
  # selected_parts: ["0","1","2","3","4","5","6","7","8"]
  selected_parts: ["0"]    # 只选择全脸的照片

# select_model: "ResNet"   # 可以选择 "Unet++" , "ResNet" 

## ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d',
#  'resnet152',  'efficientnet-b3', 'efficientnet-b4', 'efficientnet-b5', 'efficientnet-b6', 'efficientnet-b7'
#  'resnet34', 'resnet50', 
#  'resnet18',
model:
  encoder_names: ['resnet18']
  in_channels: 3
  num_classes_seg: 3
  num_classes_cls: 6 
  cls_head_type: 'sfp'  # 'sfp', 'sample'
  pretrained: true
  use_segmentation: True
  use_classification: True
  
device:
  gpus: [0, 1, 2 ]
seed: 42
logpath: "./weight/wrinkle/resnet/loss_log_wrinkle_train.log"
result_path: "./test"
mode: val   # val  or train

save_plots:
    roc_curve: True
    confusion_matrix: True
